### PR TITLE
Show help when no argument / Wrong argument/ -help / --help supplied

### PR DESCRIPTION
**Pull request by tarungarg546**
image

Please Review @lrlna

### CODE REVIEW

**Comment by lrlna** [comment]
howdy! Thanks so much for pointing it out @tarungarg546  🎉 . I am actually using [yargs](https://github.com/yargs/yargs) that could be enabled to include all the `help` messages if none are provided. Pretty neat API ^.^  Writing out the entire help message would probably be unnecessary if `.help` is enabled. If you like, you can try to implement that portion of it. Otherwise I can totally get that in there. 

Thanks again! ☀️

**Comment by tarungarg546** [comment]
@lrlna .
Already working on it.

**Comment by tarungarg546** [comment]
Hey @lrlna 

I got stuck in `yargs` somewhere.

On my machine [Windows :lollipop: with git bash] when i tried to do something like

``` js
 require('yargs')
  .usage(`Usage :-
  $0 -f [/path/to/keys/] -n [name] [platform]`)
```

`$0` for me is throwing whole path of my index.js file instead of the expected command `twitter-node-name` is this behaviour correct?

FYI, I am asking you directly because i see you are a contributor to `yargs` itself.

**Comment by CodeDotJS** [comment]
``` js
 require('yargs')
  .usage(`Usage : $0 -f [/path/to/keys/] -n [name] [platform]`)
```

First of all, you are not supposed to break `usage` like you've done.
Second, it won't show you `twitter-node-name` because file's name is `index.js`

``` json
"bin": {
    "twitter-node-name": "index.js"
  },
```

Now, when you run `node index.js` it should not show the complete path - the default structure will be -

``` js
Usage : index.js -f [/path/to/keys/] -n [name] [platform]
```

**Comment by lrlna** [comment]
@tarungarg546, did you by any chance run `npm link` when running this? 

Basically what `$0` does when running in yargs, is it takes the [script name or command](https://github.com/yargs/yargs#usagemessage-opts) you use to run the program. So if you are using `node index.js` it would take the file name. You're getting this only because it's a "development" environment, your code wil be okay in "production" ✨ 

Thanks again ☀️

**Comment by tarungarg546** [comment]
Hey @CodeDotJS ,
I am not breaking any `usage` way . I think `.usage` method expects a string and the way i have done gives more readability and spacing and using neat multiline trick of template literals, i can't see anything wrong in that.

And suppose ,
my cwd is `/somePath/different/from/where/global npm is downloaded` and `node-twitter-name` is installed globally. 
Now as a user i would expect to run my cli client to run from any cwd not just only from where my package is installed.
And now if i am in different cwd than one where package is installed and in usage if we show to user that `Usage : index.js -f [/path/to/keys/] -n [name] [platform]` and user runs exactly the same and then it would break the system and throw errors because index.js is not present in cwd

**Comment by tarungarg546** [comment]
Hey @lrlna ,

Yeah i am running through `npm ln`. 

So, as you are telling in `production` it will shown as `Usage :- $ twitter-node-name otherOpttions` than `Usage :- path someOtherOptions`?

**Comment by lrlna** [comment]
@tarungarg546 hmmm, interesting. I am going to run some tests on `yargs` itself. I don't think that should be happening when you've linked, but I am also not too familiar with a Windows environment.

**Comment by tarungarg546** [comment]
#https://github.com/yargs/yargs/issues/538

**Comment by tarungarg546** [comment]
https://github.com/yargs/yargs/issues/538

**Comment by lrlna** [comment]
@tarungarg546 if you want, you can still push the code you have here, and we can open up an issue for this Windows thing ✨

**Comment by tarungarg546** [comment]
@lrlna done.

**Comment by lrlna** [comment]
@tarungarg546 awesome! 🎉

**Comment by tarungarg546** [comment]
Hey @lrlna ,

`.choices()` is not working yet here...
I find no documentation about how to set `choices` for _argv.__.

Please let me know if you fix it.

**Pull request merged**
